### PR TITLE
New bokeh. No dummy product for GW & LegacySurvey; changeable ext_id for js9

### PR DESCRIPTION
**Pull request by dsavchenko**
PR including changes from both #123 and #128

### CODE REVIEW

**Comment by burnout87** [comment]
Do you need me to perform the same tests?

**Comment by dsavchenko** [comment]
> Do you need me to perform the same tests?

This is the same branch, I created this PR here because branches in upstream repo were disappearing. So the results will be the same. So let's just continue discussion here.

@volodymyrss what exactly was wrong in Gabriele's test results?

**Review by volodymyrss — APPROVED** [review]

**Comment by volodymyrss** [comment]
> > Do you need me to perform the same tests?
> 
> This is the same branch, I created this PR here because branches in upstream repo were disappearing. So the results will be the same. So let's just continue discussion here.
> 
> @volodymyrss what exactly was wrong in Gabriele's test results?

Nothing was distinctly wrong, but the dummy products for INTEGRAL were not quite as informative as we'd like to. But all seems good, and the new sliders are much better. Thanks!

**Comment by volodymyrss** [comment]
If it's the same branch I suggest not to re-test and merge.

**Review by burnout87 — APPROVED** [review]

**Comment by dsavchenko** [comment]
Ok, I will merge. Then we have to ensure that changes are not overwritten by gitlab sync (or whatever was the cause of disappearing branches)

**Comment by volodymyrss** [comment]
It did get overwritten. I remove sync for this repo, create a new PR, and merge

**Comment by volodymyrss** [comment]
We have to discuss with @motame , and it would be best to do it in advance. But it seems that by now changes of @burnout87 and @dsavchenko are sufficiently useful to allow occasional semi-independent development, especially if @motame is away. We can still keep the gitlab as the reference copy in full control of @motame , but occasionally the published github copy may diverge with some simple additions.
If it's ok for you @dsavchenko @burnout87 ? Or if not, we can just wait until @motame  is back.

**Comment by burnout87** [comment]
My main part of development is basically done for the frontend, so in case any additional changes is required, I should do that on github, right? Or we should use the gitlab? With @motame we had discussed this in the past and agreed to use gitlab for the development.

How does it work with sync of the github content towards gitlab? I recalled this was not as immediate as in the opposite direction.

**Comment by volodymyrss** [comment]
> My main part of development is basically done for the frontend, so in case any additional changes is required, I should do that on github, right? Or we should use the gitlab? With @motame we had discussed this in the past and agreed to use gitlab for the development.

This arrangement was good for the time but given more active frontend development including some contributions of @dsavchenko, who can not see the gitlab, it is not always applicable. 

It's fine if you continue using gitlab with @motame to agree on the **"editor's cut"** copy.

But the version on github may diverge occasionally. So the github version will the be the **"community version"**.

We should discuss later with @motame again, in two weeks.

> How does it work with sync of the github content towards gitlab? I recalled this was not as immediate as in the opposite direction.

Sync from github to gitlab is not currently done automatically and is not possible in this gitlab instance without custom additions. This matched the intention that gitlab astrooda is the reference source managed by @motame and hence should not be affected by synced merges from github.

The changes on frontend-astrooda github should be then manually merged back to gitlab when @motame is there. You could take care of this since you work with @motame the most.

And because of technical problem of gitlab automated sync destroying any additions on github, the sync has to be removed.

**Comment by volodymyrss** [comment]
Let's eventually continue there https://github.com/oda-hub/doc-handbook/pull/19

**Pull request merged**
