### PR TITLE
Allow user to set maximum number of pointings and  data rights scope (request to analyse private data); some text adaptations

### PR DESCRIPTION
**Pull request by volodymyrss**

### CODE REVIEW

**Review by motame — APPROVED** [review]
Would you please clarify ? for my knowledge ... Does it mean that the user is allowed to define the maximum number of pointings ?

**Comment by volodymyrss** [comment]
> Would you please clarify ? for my knowledge ... Does it mean that the user is allowed to define the maximum number of pointings ?

Exactly! Maximum number of pointings and also data rights scope (request to analyse private data)

**Comment by volodymyrss** [comment]
Sorry I forgot to push the commit with the data rights and text changes.

**Comment by volodymyrss** [comment]
Since you approved I  merge. Even if there were small further changes. I hope it's ok - since the principle was approved.

**Pull request merged**
