### PR TITLE
Make request fix

### PR DESCRIPTION
**Pull request by burnout87**
Should also be fixing the make progress message displaying

### CODE REVIEW

**Review by volodymyrss — APPROVED** [review]
Thanks for asking me for a review, it's good to see what happens!

**Comment by motame** [comment]
Oups ! I missed this ...
I mixed the different changes and pushed to reference.

**Comment by burnout87** [comment]
> Oups ! I missed this ...
> I mixed the different changes and pushed to reference.

Np problem. I am resolving some conflicts and we take it from there

**Comment by motame** [comment]
I don't know what should be done now !!!

**Comment by motame** [comment]
Cool ! thanks

**Comment by burnout87** [comment]
> Cool ! thanks

You can check now

**Pull request merged**
